### ISSUE TITLE
爱奇艺网站的视频无法获取地址

### ISSUE THREAD

**Issue by showzhi** [keygle/parseVideo#2]
作者你好，我在使用爱奇艺的时候，发生了问题，无法获爱奇艺的视频地址

**Comment by jiangli373** [comment]
我提交了一个pr，能解析到爱奇艺的视频下载地址  https://github.com/keygle/parseVideo/pull/5

**Comment by keygle** [comment]
合并了。谢谢。

**Comment by showzhi** [comment]
能告诉我你们解析别人的地址的思路吗，我看你们程序里面各种“与或”的处理，而且还有一些特定的时间戳数字之类的，都是怎么知道的

**Comment by jiangli373** [comment]
@showzhi 我自己的做法是抓视频网站的http请求，然后分析网站的js文件，反编译网站的视频播放器，结合http请求，找到里面的加密方法

**Comment by showzhi** [comment]
@jiangli373 能提供一些工具吗，也好让我少走一些弯路，先谢过了

**Comment by jiangli373** [comment]
@showzhi 我也没有用一些额外的工具，抓http请求的话，我用的是chrome，可以使用开发者工具就可以了，反编译播放器的话，网上有在线的反编译工具，js的话，一般都是混淆，网上也有在线反混淆的工具，可以直接使用的

**Comment by showzhi** [comment]
@jiangli373 OK了解了，谢了
